[build]
  functions = "functions"

[context.production.environment]
  DOMAIN = "app.abrevo.co"

[[headers]]
  for = "/*"
  [headers.values]
    X-Custom-Domain = "app.abrevo.co"
[functions]
  node_bundler = "esbuild"
[functions."readmail"]
  schedule = "* * * * *"
  node_bundler = "nft"
[functions."fubsync"]
  schedule = "* * * * *"
  node_bundler = "nft"
[functions."autocall"]
  schedule = "* * * * *"
  node_bundler = "nft"
[functions."healthcheck"]
  schedule = "*/30 * * * *"
  node_bundler = "nft"
[functions."sendsurvey"]
  schedule = "0 22 * * *"
  node_bundler = "nft"
[functions."followup"]
  schedule = "0 10 * * *"
  node_bundler = "nft"
[[redirects]]
  from = "/social.html"
  to = "/social.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
